# Generated by Django 3.2.4 on 2021-07-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210706_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercount',
            fields=[
                ('roomName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('roomUrl', models.CharField(max_length=100)),
                ('userCount', models.IntegerField()),
            ],
        ),
    ]
