# Generated by Django 3.2.4 on 2021-07-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('board', '0002_alter_point_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_list_write',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.b_list_write')),
            ],
        ),
    ]
